[project]
name = "audio-to-notes"
version = "0.1.0"
description = "audio-to-notes"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.93.0",
    "openai-whisper>=20250625",
    "pydub>=0.25.1",
    "python-dotenv>=1.1.1",
]
